### ISSUE TITLE
support Ruby 1.8.7

### ISSUE THREAD

**Issue by rtgibbons** [pauldowman/balisong#4]
On line 52 in app/models/page.rb you use keep_if

keep_if function for arrays was introduced in ruby 1.9.2. I'm stuck on 1.8.7, which can run rails3, and found https://github.com/marcandre/backports

A simple patch will include this gem if ruby 1.8 is used https://gist.github.com/863625

**Comment by pauldowman** [comment]
I'd be happy to do that, but I tested that with 1.8.7 and there is a failing cucumber test:

```
comparison of Page with Page failed (ArgumentError)
./app/controllers/application_controller.rb:7:in `sort'
./app/controllers/application_controller.rb:7:in `populate_site_menu'
./features/step_definitions/custom_web_steps.rb:2:in `/^(?:|I )go to the path "(.+)"$/'
features/site_menu.feature:14:in `When I go to the path "/tequila"'

Failing Scenarios:
cucumber features/site_menu.feature:7 # Scenario: 
```

I'm not sure that I want to do the work required to support 1.8.7 (fixing this, and testing under both ruby versions in the future).

**Comment by rtgibbons** [comment]
I understand that. I'm on a ruby ee 1.8.7 and don't see any problems. I haven't used cucumber before so I'm reading up on that. 

Maybe just a not on the readme would suffice (or if it's there tell me to RTFM)

**Comment by pauldowman** [comment]
To run the cucumber tests you can do "rake cucumber". You'll need to pull in my most recent update before doing that (rake cucumber didn't work because of a dependency on ActiveRecord but I didn't notice since I use autotest).

If "rake spec cucumber" passes then the RSpec and Cucumber tests are all OK, and it probably works. But I get the error above.

**Comment by pauldowman** [comment]
Oh, and thanks for the suggestion, I'll add a note in the README about running the tests.

**Comment by rtgibbons** [comment]
It's working on my server, but I had a few minutes before lunch and took a look. It is failing with the sort. Adding the function .to_i to the end of each sort value moved the test along, but now it is actually failing at the match.

I need to dig in a bit more into Cucumber to learn better way to debug from the test infroatmion as that took me too long to figure out :)

**Comment by pauldowman** [comment]
I added the backports gem as requested, but there's still that failing comparison and I haven't had a chance to investigate. I'm not sure if GitModel actually works with 1.8.7.

**Comment by rtgibbons** [comment]
I took a look at this again, at my server and my laptop. My server is running rubyee 1.8.7. I installed this on my laptop and including the backports; all the test pass. With MRI Ruby 1.8.7 it is failing. Which explains why it is working on my server. (Both Balisong and GitModel)

Maybe that's enough? How many interpreters is a project suppose to support? Especially older versions. :)

**Comment by rtgibbons** [comment]
Little interesting nugget

ruby-1.8.7 ran test in 42.652
ree-1.8.7  ran in 29.250
ruby-1.9.2 ran in 16.611

**Comment by pauldowman** [comment]
Closing. I can't officially support 1.8.7, but I'm glad that it's working for you on REE.
