### ISSUE TITLE
Missing index keys cause balisong to error

### ISSUE THREAD

**Issue by gf3** [pauldowman/balisong#7]
Missing index keys cause balisong to error. This might be the case if an expected key is not used anywhere in the content repo. For example, if one does not have pages and never references `site_menu_position` in their `attributes.json`, then balisong will fail when doing some of it's `Pages.find_all` calls.

**Comment by pauldowman** [comment]
Hmm, this might really be a GitModel issue. I think GitModel should consider an attribute that doesn't exist to be the same as one that's defined but null.

I opened pauldowman/gitmodel#4 to address that.
